package io.github.coder013.flyway.rollback;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.util.List;

public class RollbackHistoryRepository {

    private static final Logger log = LoggerFactory.getLogger(RollbackHistoryRepository.class);

    private final JdbcTemplate jdbcTemplate;
    private final String tableName;

    public RollbackHistoryRepository(DataSource dataSource, String tableName) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
        this.tableName = tableName;
        createTableIfNotExists();
    }

    private void createTableIfNotExists() {
        String quoted = "\"" + tableName + "\"";
        String sql = "CREATE TABLE IF NOT EXISTS " + quoted + " (" +
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "\"target_version\" VARCHAR(100) NOT NULL, " +
                "\"rolled_back_versions\" VARCHAR(1000) NOT NULL, " +
                "\"dry_run\" BOOLEAN NOT NULL DEFAULT FALSE, " +
                "\"executed_at\" TIMESTAMP NOT NULL" +
                ")";
        jdbcTemplate.execute(sql);
        log.debug("Rollback history table '{}' ensured.", tableName);
    }

    public void record(String targetVersion, List<String> rolledBackVersions, boolean dryRun) {
        String quoted = "\"" + tableName + "\"";
        jdbcTemplate.update(
                "INSERT INTO " + quoted + " (\"target_version\", \"rolled_back_versions\", \"dry_run\", \"executed_at\") VALUES (?, ?, ?, ?)",
                targetVersion,
                String.join(",", rolledBackVersions),
                dryRun,
                LocalDateTime.now()
        );
        log.info("Rollback history recorded: targetVersion={}, rolledBackVersions={}, dryRun={}",
                targetVersion, rolledBackVersions, dryRun);
    }
}
